version: '3'
networks:
  fila:
  app:
  banco:
services:
  rabbitmq:
    image: rabbitmq
    ports:
      - 5672
    networks:
      - fila
  
  mongo:
    image: mongo:3.4
    networks:
      - banco
  
  api-transacao:
    #build: api-transacao
    image: node:8.1
    working_dir: /api-transacao
    volumes: 
      - ./api-transacao:/api-transacao
    ports:
      - 8080:8080
    command: bash -c "cd /api-transacao && npm i && npm run build && npm start"
    networks:
      - app
      - fila
      - banco
    depends_on:
      - rabbitmq
      - mongo

  api-foo:
    #build: api-foo
    image: node:8.1
    volumes:
      - ./api-foo:/api-foo
    ports:
      - 3000:3000
    command: bash -c "cd /api-foo && npm i && npm run build && npm start"
    networks:
      - app
      - banco
    depends_on:
      - mongo

  api-fighters:
    #build: api-fighters
    image: node:8.1
    volumes:
      - ./api-fighters:/api-fighters
    ports:
      - 4000:4000
    command: bash -c "cd /api-fighters && npm i && npm run build && npm start"
    networks:
      - app
      - banco
    depends_on:
      - mongo

  worker-transacao:
    #build: worker-transacao
    image: node:8.1
    volumes:
      - ./worker-transacao:/worker-transacao
    command: bash -c "cd /worker-transacao && npm i && npm run build && npm start"
    networks: 
      - app
      - fila
      - banco
    depends_on:
      - rabbitmq
      - mongo
      - api-transacao
      - api-foo
      - api-fighters