version: '3'
networks:
  fila:
  app:
  banco:
services:
  rabbitmq:
    image: rabbitmq
    ports:
      - 5672
    networks:
      - fila

  mongo:
    image: mongo:3.4
    networks:
      - banco

  # Testes do container de api-foo      
  api-foo-test:
    image: node:8.1
    volumes:
      - ./api-foo:/api-foo
    working_dir: /api-foo
    ports:
      - 3000:3000
    command: bash -c "cd /api-foo && npm i && npm run test"
    networks:
      - app
      - banco
    depends_on:
      - mongo  

  # Testes do container de api-fighters
  api-fighters-test:
    image: node:8.1
    volumes:
      - ./api-fighters:/api-fighters
    working_dir: /api-fighters
    ports:
      - 4000:4000
    command: bash -c "cd /api-fighters && npm i && npm run test"
    networks:
      - app
      - banco
    depends_on:
      - mongo  

  # Testes do container de api-transacao
  api-transacao-test:
    image: node:8.1
    volumes:
      - ./api-transacao:/api-transacao
    ports:
      - 8080:8080
    command: bash -c "cd /api-transacao && npm i && npm run test"
    networks:
      - app
      - fila
      - banco
    depends_on:
      - rabbitmq
      - mongo
  
  # Testes do container de worker transacao
  worker-transacao-test:
    image: node:8.1
    volumes:
      - ./worker-transacao:/worker-transacao
    command: bash -c "cd /worker-transacao && npm i && npm run test"
    networks:
      - app
      - fila
      - banco
    depends_on:
      - rabbitmq
      - mongo
      - api-foo-dev-test
      - api-fighters-dev-test
  
  # Testes de falha do container de worker transacao
  worker-transacao-test-fail:
    image: node:8.1
    volumes:
      - ./worker-transacao:/worker-transacao
    command: bash -c "cd /worker-transacao && npm i && npm run test:fail"
    networks:
      - app
      - fila
      - banco
    depends_on:
      - rabbitmq
      - mongo

  # Container da api-foo rodando em dev com configurações de teste
  # para integração com os testes de worker-transacao      
  api-foo-dev-test:
    image: node:8.1
    volumes:
      - ./api-foo:/api-foo
    ports:
      - 3001:3001
    command: bash -c "cd /api-foo && npm i && npm run dev:test"
    networks:
      - app
      - banco
    depends_on:
      - mongo

  # Container da api-fighters rodando em dev com configurações de teste
  # para integração com os testes de worker-transacao      
  api-fighters-dev-test:
    image: node:8.1
    volumes:
      - ./api-fighters:/api-fighters
    ports:
      - 4001:4001
    command: bash -c "cd /api-fighters && npm i && npm run dev:test"
    networks:
      - app
      - banco
    depends_on:
      - mongo
#sudo docker-compose -f ./docker-compose-test.yml up api-foo-test
#sudo docker-compose -f ./docker-compose-test.yml up api-fighters-test
#sudo docker-compose -f ./docker-compose-test.yml up api-transacao-test
#sudo docker-compose -f ./docker-compose-test.yml up worker-transacao-test
