version: '3'
networks:
  fila:
  app:
  banco:
services:
  rabbitmq:
    image: rabbitmq
    ports:
      - 5672
    networks:
      - fila

  mongo:
    image: mongo:3.4
    networks:
      - banco

  api-transacao-test:
    image: node:8.1
    volumes:
      - ./api-transacao:/api-transacao
    working_dir: /transacao
    ports:
      - 8080:8080
    command: bash -c "cd /api-transacao && npm i && npm run test"
    networks:
      - app
      - fila
      - banco
    depends_on:
      - rabbitmq
      - mongo

#sudo docker-compose -f ./docker-compose.api-transacao-test.yml up
